sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mongodb

before_script:
  - pecl install -f mongodb
  - composer install

script: ./bin/phpunit --coverage-text

notifications:
  email: false
